//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class payments
    {
        public int portfolio_id { get; set; }
        public int establishment_id { get; set; }
        public string establishment_name { get; set; }
        public int customer_number { get; set; }
        public double user_balance { get; set; }
        public double payment_amount { get; set; }
    
        public virtual establishment establishment { get; set; }
        public virtual portfolio portfolio { get; set; }
    }
}
