//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class portfolio
    {
        public int user_portfolio_id { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<double> daily_income { get; set; }
        public Nullable<double> daily_expense { get; set; }
        public Nullable<double> non_cash_assest { get; set; }
        public Nullable<int> registered_debit_cards { get; set; }
    
        public virtual payments payments { get; set; }
        public virtual user_debit_cards user_debit_cards { get; set; }
        public virtual users users { get; set; }
    }
}
